      SUBROUTINE LLIKE(NX,X,INTS,NINT,DOUBLS,NDOUB,TMAT,NTMAT,IMAT,&
     &                 NIMAT,OMAT,NOMAT,NOBS,NSET,NMISST,FPEN,FPRIOR,&
     &                 EPSM,JOB,FUNK,INFO,VX0)
     
      INTEGER          NX,NINT,INTS(NINT),NDOUB,NTMAT,NIMAT,NOMAT,NSET,&
     &                 NOBS(NSET),NMISST,JOB,INFO,VX0
      DOUBLE PRECISION X(NX),DOUBLS(NDOUB),TMAT(NTMAT),IMAT(NIMAT),&
     &                 OMAT(NOMAT),EPSM,FUNK
     
      END